"""LLM service — Ollama client via OpenAI-compatible API.

Routes all inference to llm-prod-lt01 (10.30.30.10:11434/v1).
GDPR-compliant: zero cross-border data transfer, EU-only inference.

SOC 2 CC6.6 — Logical access security
GDPR Art. 32 — Security of processing
"""

from __future__ import annotations

from prometheus_client import Counter, Histogram
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from app.audit import get_logger
from app.config import Settings, get_settings

# --- Prometheus metrics ---
LLM_LATENCY = Histogram(
    "rag_llm_generation_duration_seconds",
    "LLM generation latency",
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0),
)
LLM_TOKENS = Counter(
    "rag_llm_tokens_generated_total",
    "Total tokens generated by LLM",
)
LLM_ERRORS = Counter(
    "rag_llm_errors_total",
    "Total LLM call errors",
)

logger = get_logger()


class LLMService:
    """Interface to Ollama LLM via OpenAI-compatible API."""

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._client = None

    def _get_client(self):
        """Lazy-initialise the OpenAI-compatible client.

        When internal TLS is enabled, an httpx client presenting a
        client certificate (mTLS) and verifying the internal CA is used.
        """
        if self._client is None:
            from openai import OpenAI

            kwargs = {}
            if self._settings.rag_internal_tls_enabled:
                import httpx

                tls_kwargs: dict = {
                    "verify": str(self._settings.rag_tls_ca_cert)
                    if self._settings.rag_tls_ca_cert
                    else True,
                }
                if (
                    self._settings.rag_tls_client_cert
                    and self._settings.rag_tls_client_key
                ):
                    tls_kwargs["cert"] = (
                        str(self._settings.rag_tls_client_cert),
                        str(self._settings.rag_tls_client_key),
                    )
                kwargs["http_client"] = httpx.Client(**tls_kwargs)

            self._client = OpenAI(
                base_url=self._settings.ollama_endpoint,
                api_key="ollama",  # Ollama does not require a real key
                timeout=self._settings.ollama_timeout,
                **kwargs,
            )
        return self._client

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=60),
        retry=retry_if_exception_type((ConnectionError, TimeoutError)),
        reraise=True,
    )
    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> str:
        """Generate a completion from the LLM.

        Args:
            prompt: The user prompt / question with context.
            system_prompt: Optional system instruction.
            temperature: Sampling temperature (default from settings).
            max_tokens: Maximum tokens to generate (default from settings).

        Returns:
            Generated text response.
        """
        client = self._get_client()
        messages = []

        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        try:
            with LLM_LATENCY.time():
                response = client.chat.completions.create(
                    model=self._settings.ollama_model,
                    messages=messages,
                    temperature=temperature or self._settings.ollama_temperature,
                    max_tokens=max_tokens or self._settings.ollama_max_tokens,
                )

            content = response.choices[0].message.content or ""
            tokens_used = response.usage.completion_tokens if response.usage else 0
            LLM_TOKENS.inc(tokens_used)

            logger.debug(
                "llm_generation_complete",
                model=self._settings.ollama_model,
                tokens=tokens_used,
            )
            return content

        except Exception as exc:
            LLM_ERRORS.inc()
            logger.error("llm_generation_failed", error=str(exc))
            raise

    def health_check(self) -> bool:
        """Check Ollama endpoint connectivity."""
        try:
            client = self._get_client()
            models = client.models.list()
            return len(models.data) > 0
        except Exception:
            return False


# Module-level singleton
_service: LLMService | None = None


def get_llm_service() -> LLMService:
    """Return the module-level LLM service singleton."""
    global _service  # noqa: PLW0603
    if _service is None:
        _service = LLMService()
    return _service
