#!/usr/bin/env bash
# =============================================================================
# vault-inject-secrets.sh — Render /opt/jol/rag/.env from HashiCorp Vault
#
# Reads all RAG secrets from the Vault KV v2 path and writes the .env file
# consumed by docker compose. Run on rag-prod-lt01 after Vault login:
#
#   export VAULT_ADDR=https://vault.jol.internal:8200
#   vault login -method=oidc     # or token/approle in automation
#   sudo -E bash scripts/vault-inject-secrets.sh
#
# Secrets never touch the repo, shell history, or CI logs.
# SOC 2 CC6.1 / ISO 27001 A.8.24 — Secrets management
# =============================================================================
set -euo pipefail

# Any incidental file created before the explicit chmod/install must be
# owner-only (defence in depth; install still forces 640 on .env).
umask 077

VAULT_PATH="${VAULT_PATH:-secret/data/jol/rag/prod}"
ENV_FILE="${ENV_FILE:-/opt/jol/rag/.env}"

command -v vault >/dev/null 2>&1 || { echo "ERROR: vault CLI not installed." >&2; exit 1; }

echo "Fetching secrets from Vault path: $VAULT_PATH"
SECRETS_JSON="$(vault kv get -format=json "$VAULT_PATH")"

get_secret() {
  echo "$SECRETS_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['data']['data']['$1'])"
}

TMP_FILE="$(mktemp)"
chmod 600 "$TMP_FILE"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<EOF
# Generated by vault-inject-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT EDIT BY HAND — re-run the script after Vault changes.
RAG_JWT_SECRET=$(get_secret jwt_secret)
RAG_HMAC_SALT=$(get_secret hmac_salt)
QDRANT_API_KEY=$(get_secret qdrant_api_key)
MINIO_ROOT_USER=$(get_secret minio_root_user)
MINIO_ROOT_PASSWORD=$(get_secret minio_root_password)
REDIS_PASSWORD=$(get_secret redis_password)
EOF

# Atomic install: root-owned, readable only by root + jol-rag group
install -m 640 -o root -g root "$TMP_FILE" "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 640). Restart services to apply: docker compose restart"
